import 'package:flutter/material.dart';

import 'top_half.dart';

class RootPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            expandedHeight: 230,
            collapsedHeight: 130,
            floating: true,
            pinned: true,
            flexibleSpace: MainStuff(),
          ),
          SliverList(
              delegate: SliverChildListDelegate([
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
                Text("Task Goes here"),
              ])
          )
        ],
      ),
      drawer: Drawer(),
    );
  }
}